// export const rawMenus: SiteRoute.RowRoute[] = [
//   // 基础功能
//   {
//     id: '1',
//     pid: '0',
//     name: 'home',
//     path: '/index',
//     componentPath: '/workbench/index.vue',
//     title: '首页',
//     icon: 'icon-park-outline:home',
//     keepAlive: false,
//     visible: true,
//     sort: '1',
//     pined: true,
//     menuType: '1',
//   },
//   {
//     id: '2',
//     pid: '0',
//     name: 'dashboard',
//     path: '/dashboard',
//     componentPath: '/dashboard/index.vue',
//     title: '仪表盘',
//     icon: 'icon-park-outline:dashboard',
//     keepAlive: false,
//     visible: true,
//     sort: '2',
//     pined: false,
//     menuType: '1',
//   },

//   // 系统管理分组
//   {
//     id: '10019',
//     pid: '0',
//     name: 'system_permisson',
//     path: '/authority',
//     componentPath: null,
//     title: '权限管理',
//     icon: 'icon-park-outline:setting-config',
//     keepAlive: false,
//     visible: true,
//     sort: '4',
//     pined: false,
//     menuType: '0',
//   },
//   {
//     id: '103',
//     pid: '10019',
//     name: 'role',
//     path: '/biz/role',
//     componentPath: '/modular/sys/role/index.vue',
//     title: '角色管理',
//     icon: 'icon-park-outline:people-safe',
//     keepAlive: false,
//     visible: true,
//     sort: '3',
//     pined: false,
//     menuType: '1',
//   },
//   {
//     id: '105',
//     pid: '10019',
//     name: 'group',
//     path: '/biz/group',
//     componentPath: '/modular/sys/group/index.vue',
//     title: '用户组管理',
//     icon: 'icon-park-outline:peoples',
//     keepAlive: false,
//     visible: true,
//     sort: '5',
//     pined: false,
//     menuType: '1',
//   },

//   {
//     id: '104',
//     pid: '0',
//     name: 'user',
//     path: '/biz/user',
//     componentPath: '/modular/sys/user/index.vue',
//     title: '用户管理',
//     icon: 'icon-park-outline:user',
//     keepAlive: false,
//     visible: true,
//     sort: '4',
//     pined: false,
//     menuType: '1',
//   },
//   // 系统管理分组
//   {
//     id: '100',
//     pid: '0',
//     name: 'system_index',
//     path: '/system',
//     componentPath: null,
//     title: '发布管理',
//     icon: 'icon-park-outline:setting-config',
//     keepAlive: false,
//     visible: true,
//     sort: '4',
//     pined: false,
//     menuType: '0',
//   },
//   {
//     id: '101',
//     pid: '100',
//     name: 'banner',
//     path: '/biz/banner',
//     componentPath: '/modular/sys/banner/index.vue',
//     title: '横幅管理',
//     icon: 'icon-park-outline:ad-product',
//     keepAlive: false,
//     visible: true,
//     sort: '1',
//     pined: false,
//     menuType: '1',
//   },
//   {
//     id: '102',
//     pid: '100',
//     name: 'notice',
//     path: '/biz/notice',
//     componentPath: '/modular/sys/notice/index.vue',
//     title: '公告管理',
//     icon: 'icon-park-outline:volume-notice',
//     keepAlive: false,
//     visible: true,
//     sort: '2',
//     pined: false,
//     menuType: '1',
//   },

//   {
//     id: '1057',
//     pid: '100',
//     name: 'article',
//     path: '/biz/article',
//     componentPath: '/modular/sys/article/index.vue',
//     title: '文章管理',
//     icon: 'icon-park-outline:peoples',
//     keepAlive: false,
//     visible: true,
//     sort: '5',
//     pined: false,
//     menuType: '1',
//   },
//   {
//     id: '10574',
//     pid: '0',
//     name: 'config',
//     path: '/biz/config',
//     componentPath: '/modular/sys/config/index.vue',
//     title: '配置管理',
//     icon: 'icon-park-outline:peoples',
//     keepAlive: false,
//     visible: true,
//     sort: '5',
//     pined: false,
//     menuType: '1',
//   },

//   {
//     id: '106',
//     pid: '0',
//     name: 'dict',
//     path: '/biz/dict',
//     componentPath: '/modular/sys/dict/index.vue',
//     title: '字典管理',
//     icon: 'icon-park-outline:book',
//     keepAlive: false,
//     visible: true,
//     sort: '6',
//     pined: false,
//     menuType: '1',
//   },

//   // // 分类标签分组
//   // {
//   //   id: '200',
//   //   pid: '0',
//   //   name: 'classification_index',
//   //   path: '/classification',
//   //   componentPath: null,
//   //   title: '分类标签',
//   //   icon: 'icon-park-outline:category-management',
//   //   keepAlive: false,
//   //   visible: true,
//   //   sort: '5',
//   //   pined: false,
//   //   menuType: '0',
//   // },
//   {
//     id: '201',
//     pid: '0',
//     name: 'category',
//     path: '/biz/category',
//     componentPath: '/modular/category/index.vue',
//     title: '分类管理',
//     icon: 'icon-park-outline:category-management',
//     keepAlive: false,
//     visible: true,
//     sort: '1',
//     pined: false,
//     menuType: '1',
//   },
//   {
//     id: '202',
//     pid: '0',
//     name: 'tag',
//     path: '/biz/tag',
//     componentPath: '/modular/tag/index.vue',
//     title: '标签管理',
//     icon: 'icon-park-outline:tag',
//     keepAlive: false,
//     visible: true,
//     sort: '2',
//     pined: false,
//     menuType: '1',
//   },

//   // 题目管理分组
//   {
//     id: '300',
//     pid: '0',
//     name: 'problem_index',
//     path: '/problem',
//     componentPath: null,
//     title: '题目管理',
//     icon: 'icon-park-outline:edit',
//     keepAlive: false,
//     visible: true,
//     sort: '6',
//     pined: false,
//     menuType: '0',
//   },
//   {
//     id: '301',
//     pid: '300',
//     name: 'problem',
//     path: '/biz/problem',
//     componentPath: '/modular/problem/problem/index.vue',
//     title: '题目列表',
//     icon: 'icon-park-outline:list',
//     keepAlive: false,
//     visible: true,
//     sort: '1',
//     pined: false,
//     menuType: '1',
//   },
//   {
//     id: '302',
//     pid: '300',
//     name: 'submit',
//     path: '/biz/problem/submit',
//     componentPath: '/modular/problem/submit/index.vue',
//     title: '题目提交',
//     icon: 'icon-park-outline:upload',
//     keepAlive: false,
//     visible: true,
//     sort: '2',
//     pined: false,
//     menuType: '1',
//   },
//   {
//     id: '303',
//     pid: '300',
//     name: 'solved',
//     path: '/biz/problem/solved',
//     componentPath: '/modular/problem/solved/index.vue',
//     title: '解决记录',
//     icon: 'icon-park-outline:checklist',
//     keepAlive: false,
//     visible: true,
//     sort: '3',
//     pined: false,
//     menuType: '1',
//   },
//   {
//     id: '304',
//     pid: '300',
//     name: 'problem_rank',
//     path: '/biz/problem/ranking',
//     componentPath: '/modular/problem/ranking/index.vue',
//     title: '题目排行榜',
//     icon: 'icon-park-outline:ranking',
//     keepAlive: false,
//     visible: true,
//     sort: '4',
//     pined: false,
//     menuType: '1',
//   },

//   // 题集管理分组
//   {
//     id: '400',
//     pid: '0',
//     name: 'set_index',
//     path: '/set',
//     componentPath: null,
//     title: '题集管理',
//     icon: 'icon-park-outline:folder',
//     keepAlive: false,
//     visible: true,
//     sort: '7',
//     pined: false,
//     menuType: '0',
//   },
//   {
//     id: '401',
//     pid: '400',
//     name: 'set',
//     path: '/biz/set',
//     componentPath: '/modular/set/set/index.vue',
//     title: '题集列表',
//     icon: 'icon-park-outline:list',
//     keepAlive: false,
//     visible: true,
//     sort: '1',
//     pined: false,
//     menuType: '1',
//   },
//   {
//     id: '402',
//     pid: '400',
//     name: 'set_submit',
//     path: '/set/submit',
//     componentPath: '/modular/set/submit/index.vue',
//     title: '题集提交',
//     icon: 'icon-park-outline:upload',
//     keepAlive: false,
//     visible: true,
//     sort: '2',
//     pined: false,
//     menuType: '1',
//   },
//   {
//     id: '403',
//     pid: '400',
//     name: 'set_solved',
//     path: '/set/solved',
//     componentPath: '/modular/set/solved/index.vue',
//     title: '解决记录',
//     icon: 'icon-park-outline:checklist',
//     keepAlive: false,
//     visible: true,
//     sort: '3',
//     pined: false,
//     menuType: '1',
//   },
//   {
//     id: '404',
//     pid: '400',
//     name: 'set_ranking',
//     path: '/set/ranking',
//     componentPath: '/modular/set/ranking/index.vue',
//     title: '题集排行榜',
//     icon: 'icon-park-outline:ranking',
//     keepAlive: false,
//     visible: true,
//     sort: '4',
//     pined: false,
//     menuType: '1',
//   },
//   {
//     id: '4041',
//     pid: '400',
//     name: 'set_progress',
//     path: '/set/progress',
//     componentPath: '/modular/set/progress/index.vue',
//     title: '进度管理',
//     icon: 'icon-park-outline:ranking',
//     keepAlive: false,
//     visible: true,
//     sort: '4',
//     pined: false,
//     menuType: '1',
//   },

//   // 个人中心
//   {
//     id: '500',
//     pid: '0',
//     name: 'mine',
//     path: '/mine',
//     componentPath: null,
//     title: '我的',
//     icon: 'icon-park-outline:user',
//     keepAlive: false,
//     visible: true,
//     sort: '8',
//     pined: false,
//     menuType: '0',
//   },
// ]

export const rawMenus: SiteRoute.RowRoute[] = [
  // 基础功能
  {
    id: '1',
    pid: '0',
    name: 'home',
    path: '/index',
    componentPath: '/workbench/index.vue',
    title: '首页',
    icon: 'icon-park-outline:home',
    keepAlive: false,
    visible: true,
    sort: '1',
    pined: true,
    menuType: '1',
  },
  {
    id: '2',
    pid: '0',
    name: 'dashboard',
    path: '/dashboard',
    componentPath: '/dashboard/index.vue',
    title: '仪表盘',
    icon: 'icon-park-outline:dashboard',
    keepAlive: false,
    visible: true,
    sort: '2',
    pined: false,
    menuType: '1',
  },
  {
    id: '3',
    pid: '0',
    name: 'category',
    path: '/category',
    componentPath: '/modular/sys/category/index.vue',
    title: '分类管理',
    icon: 'icon-park-outline:category-management',
    keepAlive: false,
    visible: true,
    sort: '3',
    pined: false,
    menuType: '1',
  },
  {
    id: '4',
    pid: '0',
    name: 'tag',
    path: '/tag',
    componentPath: '/modular/sys/tag/index.vue',
    title: '标签管理',
    icon: 'icon-park-outline:tag',
    keepAlive: false,
    visible: true,
    sort: '4',
    pined: false,
    menuType: '1',
  },
  // 内容管理分组
  {
    id: '100',
    pid: '0',
    name: 'content_index',
    path: '/content',
    componentPath: null,
    title: '内容管理',
    icon: 'icon-park-outline:setting-config',
    keepAlive: false,
    visible: true,
    sort: '5',
    pined: false,
    menuType: '0',
  },
  {
    id: '101',
    pid: '100',
    name: 'banner',
    path: '/content/banner',
    componentPath: '/modular/sys/banner/index.vue',
    title: '横幅管理',
    icon: 'icon-park-outline:ad-product',
    keepAlive: false,
    visible: true,
    sort: '1',
    pined: false,
    menuType: '1',
  },
  {
    id: '102',
    pid: '100',
    name: 'notice',
    path: '/content/notice',
    componentPath: '/modular/sys/notice/index.vue',
    title: '公告管理',
    icon: 'icon-park-outline:volume-notice',
    keepAlive: false,
    visible: true,
    sort: '2',
    pined: false,
    menuType: '1',
  },
  // {
  //   id: '1057',
  //   pid: '100',
  //   name: 'article',
  //   path: '/content/article',
  //   componentPath: '/modular/sys/article/index.vue',
  //   title: '文章管理',
  //   icon: 'icon-park-outline:peoples',
  //   keepAlive: false,
  //   visible: true,
  //   sort: '3',
  //   pined: false,
  //   menuType: '1',
  // },

  // 系统管理分组
  {
    id: '10019',
    pid: '0',
    name: 'system_index',
    path: '/system',
    componentPath: null,
    title: '系统管理',
    icon: 'icon-park-outline:setting-config',
    keepAlive: false,
    visible: true,
    sort: '4',
    pined: false,
    menuType: '0',
  },
  {
    id: '104',
    pid: '10019',
    name: 'user',
    path: '/system/user',
    componentPath: '/modular/sys/user/index.vue',
    title: '用户管理',
    icon: 'icon-park-outline:user',
    keepAlive: false,
    visible: true,
    sort: '1',
    pined: false,
    menuType: '1',
  },
  {
    id: '103',
    pid: '10019',
    name: 'role',
    path: '/system/role',
    componentPath: '/modular/sys/role/index.vue',
    title: '角色管理',
    icon: 'icon-park-outline:people-safe',
    keepAlive: false,
    visible: true,
    sort: '2',
    pined: false,
    menuType: '1',
  },
  {
    id: '105',
    pid: '10019',
    name: 'group',
    path: '/system/group',
    componentPath: '/modular/sys/group/index.vue',
    title: '用户组管理',
    icon: 'icon-park-outline:peoples',
    keepAlive: false,
    visible: true,
    sort: '3',
    pined: false,
    menuType: '1',
  },
  {
    id: '10574',
    pid: '10019',
    name: 'config',
    path: '/system/config',
    componentPath: '/modular/sys/config/index.vue',
    title: '环境变量',
    icon: 'icon-park-outline:enter-the-keyboard',
    keepAlive: false,
    visible: true,
    sort: '4',
    pined: false,
    menuType: '1',
  },
  {
    id: '106',
    pid: '10019',
    name: 'dict',
    path: '/system/dict',
    componentPath: '/modular/sys/dict/index.vue',
    title: '字典管理',
    icon: 'icon-park-outline:book',
    keepAlive: false,
    visible: true,
    sort: '5',
    pined: false,
    menuType: '1',
  },
  // 题目管理分组
  {
    id: '300',
    pid: '0',
    name: 'problem_index',
    path: '/problem',
    componentPath: null,
    title: '题目管理',
    icon: 'icon-park-outline:edit',
    keepAlive: false,
    visible: true,
    sort: '5',
    pined: false,
    menuType: '0',
  },
  {
    id: '301',
    pid: '300',
    name: 'problem',
    path: '/problem/list',
    componentPath: '/modular/problem/problem/index.vue',
    title: '题目列表',
    icon: 'icon-park-outline:list',
    keepAlive: false,
    visible: true,
    sort: '1',
    pined: false,
    menuType: '1',
  },
  {
    id: '302',
    pid: '300',
    name: 'submit',
    path: '/problem/submit',
    componentPath: '/modular/problem/submit/index.vue',
    title: '题目提交',
    icon: 'icon-park-outline:upload',
    keepAlive: false,
    visible: true,
    sort: '2',
    pined: false,
    menuType: '1',
  },
  {
    id: '303',
    pid: '300',
    name: 'solved',
    path: '/problem/solved',
    componentPath: '/modular/problem/solved/index.vue',
    title: '解决记录',
    icon: 'icon-park-outline:checklist',
    keepAlive: false,
    visible: true,
    sort: '3',
    pined: false,
    menuType: '1',
  },
  {
    id: '304',
    pid: '300',
    name: 'problem_rank',
    path: '/problem/pranking',
    componentPath: '/modular/problem/pranking/index.vue',
    title: '题目排行榜',
    icon: 'icon-park-outline:ranking',
    keepAlive: false,
    visible: true,
    sort: '4',
    pined: false,
    menuType: '1',
  },
  {
    id: '305',
    pid: '300',
    name: 'problem_user_rank',
    path: '/problem/puranking',
    componentPath: '/modular/problem/puranking/index.vue',
    title: '用户排行榜',
    icon: 'icon-park-outline:ranking',
    keepAlive: false,
    visible: true,
    sort: '5',
    pined: false,
    menuType: '1',
  },
  {
    id: '306',
    pid: '300',
    name: 'problem_sample',
    path: '/problem/sample',
    componentPath: '/modular/problem/sample/index.vue',
    title: '相似样本库',
    icon: 'icon-park-outline:data-file',
    keepAlive: false,
    visible: true,
    sort: '6',
    pined: false,
    menuType: '1',
  },
  {
    id: '307',
    pid: '300',
    name: 'problem_similarity_task',
    path: '/problem/similarity/task',
    componentPath: '/modular/problem/similarity/index.vue',
    title: '检测任务',
    icon: 'icon-park-outline:accept-email',
    keepAlive: false,
    visible: true,
    sort: '7',
    pined: false,
    menuType: '1',
  },

  // 题集管理分组
  {
    id: '400',
    pid: '0',
    name: 'set_index',
    path: '/set',
    componentPath: null,
    title: '题集管理',
    icon: 'icon-park-outline:folder',
    keepAlive: false,
    visible: true,
    sort: '6',
    pined: false,
    menuType: '0',
  },
  {
    id: '401',
    pid: '400',
    name: 'set',
    path: '/set/list',
    componentPath: '/modular/set/set/index.vue',
    title: '题集列表',
    icon: 'icon-park-outline:list',
    keepAlive: false,
    visible: true,
    sort: '1',
    pined: false,
    menuType: '1',
  },
  {
    id: '402',
    pid: '400',
    name: 'set_submit',
    path: '/set/submit',
    componentPath: '/modular/set/submit/index.vue',
    title: '题集提交',
    icon: 'icon-park-outline:upload',
    keepAlive: false,
    visible: true,
    sort: '2',
    pined: false,
    menuType: '1',
  },
  {
    id: '403',
    pid: '400',
    name: 'set_solved',
    path: '/set/solved',
    componentPath: '/modular/set/solved/index.vue',
    title: '解决记录',
    icon: 'icon-park-outline:checklist',
    keepAlive: false,
    visible: true,
    sort: '3',
    pined: false,
    menuType: '1',
  },
  {
    id: '404',
    pid: '400',
    name: 'set_progress',
    path: '/set/progress',
    componentPath: '/modular/set/progress/index.vue',
    title: '进度监控',
    icon: 'icon-park-outline:ranking',
    keepAlive: false,
    visible: true,
    sort: '4',
    pined: false,
    menuType: '1',
  },
  {
    id: '405',
    pid: '400',
    name: 'set_ranking',
    path: '/set/sranking',
    componentPath: '/modular/set/sranking/index.vue',
    title: '题集排行榜',
    icon: 'icon-park-outline:ranking',
    keepAlive: false,
    visible: true,
    sort: '5',
    pined: false,
    menuType: '1',
  },
  {
    id: '405',
    pid: '400',
    name: 'set_user_ranking',
    path: '/set/suranking',
    componentPath: '/modular/set/suranking/index.vue',
    title: '用户排行榜',
    icon: 'icon-park-outline:ranking',
    keepAlive: false,
    visible: true,
    sort: '6',
    pined: false,
    menuType: '1',
  },
  {
    id: '406',
    pid: '400',
    name: 'set_sample',
    path: '/set/sample',
    componentPath: '/modular/set/sample/index.vue',
    title: '相似样本库',
    icon: 'icon-park-outline:data-file',
    keepAlive: false,
    visible: true,
    sort: '7',
    pined: false,
    menuType: '1',
  },
  {
    id: '407',
    pid: '400',
    name: 'set_similarity_task',
    path: '/set/similarity/task',
    componentPath: '/modular/set/similarity/index.vue',
    title: '检测任务',
    icon: 'icon-park-outline:accept-email',
    keepAlive: false,
    visible: true,
    sort: '8',
    pined: false,
    menuType: '1',
  },

  // 检测报告分组
  {
    id: '500',
    pid: '0',
    name: 'report',
    path: '/report',
    componentPath: '/modular/report/index.vue',
    title: '检测报告',
    icon: 'icon-park-outline:database-download',
    keepAlive: false,
    visible: true,
    sort: '6',
    pined: false,
    menuType: '1',
  },

  // 个人中心
  {
    id: '600',
    pid: '0',
    name: 'mine',
    path: '/mine',
    componentPath: null,
    title: '个人中心',
    icon: 'icon-park-outline:user',
    keepAlive: false,
    visible: true,
    sort: '7',
    pined: false,
    menuType: '0',
  },

  
  {
    id: '7870',
    pid: '0',
    name: 'report',
    path: '/problem/submit/report/:reportId/task/:taskId',
    componentPath: '/modular/problem/submit/report.vue',
    title: '检测报告详情',
    icon: 'icon-park-outline:info',
    keepAlive: false,
    visible: false,
    sort: '9',
    pined: false,
    menuType: '1',
  },

  // 关于页面
  {
    id: '700',
    pid: '0',
    name: 'about',
    path: '/about',
    componentPath: '/about.vue',
    title: '关于',
    icon: 'icon-park-outline:info',
    keepAlive: false,
    visible: true,
    sort: '8',
    pined: false,
    menuType: '1',
  },

  // 测试页面
  {
    id: '800',
    pid: '0',
    name: 'test-1',
    path: '/test-1',
    componentPath: '/modular/test/test1.vue',
    title: 'Test-1',
    icon: 'icon-park-outline:info',
    keepAlive: false,
    visible: true,
    sort: '9',
    pined: false,
    menuType: '1',
  },
  {
    id: '801',
    pid: '0',
    name: 'test-2',
    path: '/test-2',
    componentPath: '/modular/test/test2.vue',
    title: 'Test-2',
    icon: 'icon-park-outline:info',
    keepAlive: false,
    visible: true,
    sort: '9',
    pined: false,
    menuType: '1',
  },
]
